### ISSUE TITLE
项目主页视频顺序错误

### ISSUE THREAD

**Issue by ZZfive** [open-mmlab/FoleyCrafter#1]
很棒的项目，主页中的例子效果都还不错，有两对视频顺序错位了，注意替换
![image](https://github.com/open-mmlab/FoleyCrafter/assets/57706634/866aba3d-ff1a-4d3e-9b52-3cf8a3dcc72f)

**Comment by ymzhang0319** [comment]
@ZZfive 感谢关注，事实上这些例子展示了**Negative Prompt**（负向提示词）的效果，所以音效的出现与正向提示词相反。
之后我会在主页中更醒目的说明，避免混淆。
