### ISSUE TITLE
No temporal_align flag in inference.py

### ISSUE THREAD

**Issue by avishkarsaha** [open-mmlab/FoleyCrafter#18]
I tried to run the inference command from the README (with my own input/outpout directories), but there is no `--temporal_align` flag in `inference.py`.This is the command I ran:
```
python inference.py \
--temporal_align \
--input=input/avsync \
--save_dir=output/avsync/
```
This is the error:
```
usage: inference.py [-h] [--prompt PROMPT] [--nprompt NPROMPT] [--seed SEED] [--semantic_scale SEMANTIC_SCALE]
                    [--temporal_scale TEMPORAL_SCALE] [--input INPUT] [--ckpt CKPT] [--save_dir SAVE_DIR]
                    [--pretrain PRETRAIN] [--device DEVICE]
inference.py: error: unrecognized arguments: --temporal_align
```

I'm assuming the inference script provided is an older version? Is there a version which matches the README?

**Comment by ymzhang0319** [comment]
Hi @avishkarsaha, thanks for your feedback!

I think you are right, please use **temporal_scale** instead.
