### ISSUE TITLE
The sound event onset is not aligned with the video.

### ISSUE THREAD

**Issue by yypyyds** [open-mmlab/FoleyCrafter#2]
I tried to generate the video using the demo video from the project homepage, but the output audio does not align with the gunshot events in the video at all. I noticed that the *Temporal Align Scale* is set to 0 initially and I have tried to set it to the range of 0.8 to 1, but it didn't work. Could you please give me some information about the hyperparameters setting?

**Comment by ymzhang0319** [comment]
Hi @yypyyds, thanks for your interest! 
I checked the [demo code](https://huggingface.co/spaces/ymzhang319/FoleyCrafter/blob/074103998edddb998f589dd80b38d7ad9adb918b/app.py#L186) and found that there is a bug. 
The temporal_scale is set to 0 all the time. We will fix it later.
