### ISSUE TITLE
Question on CLIP-Score Calculation

### ISSUE THREAD

**Issue by sakshamsingh1** [open-mmlab/FoleyCrafter#22]
Hi,
Thanks for the wonderful project.

I have a few questions regarding the CLIP-score calculation:

1. Could you provide more details on calculating the CLIP score? Specifically, how many frames are used to represent each video?

2. Additionally, is each frame's CLIP embedding multiplied with the audio embedding, and then is the average of these multiplications taken? Or is there a different approach used for combining the frame and audio embeddings?

**Comment by ymzhang0319** [comment]
Hi @sakshamsingh1, thx for your interest!

We use [Wav2Clip](https://github.com/descriptinc/lyrebird-wav2clip) to extract audio feature and [CLIP](https://github.com/openai/CLIP) to extract video frame features for evaluation.

1. We take one frame from every 30 frames for clip score.

2. We average the features of all sampled video frames and then calculate the similarity with the audio features.
