### ISSUE TITLE
Questions about the details of mel-spectrogram transformation

### ISSUE THREAD

**Issue by fzlittlekid** [open-mmlab/FoleyCrafter#24]
Thanks for the wonderful project.

In the Audio Latent Diffusion Model, the audio waveform is initially transformed into a mel-spectrogram representation.
Could you please provide the code or specific details of this transformation, such as FFT Num, mel basis Num, hop size, etc.

**Comment by ymzhang0319** [comment]
Hi @fzlittlekid, thanks for your interest!
We refer to our base model Auffusion for mel-spectrogram extraction.
Specifically, we set **n_fft=2048, num_mels=256, sampling_rate=16000, hop_size=160, win_size=1024, fmin=0 and fmax=8000**.
